CEC\TutoratBundle\Entity\ChangementCordeeLycee:
    type: entity
    table: null
    repositoryClass: CEC\TutoratBundle\Entity\ChangementCordeeLyceeRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        action:
            type: integer
        annee:
            type: integer
        dateCreation:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        dateModification:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        cordee:
            targetEntity: Cordee
            inversedBy: changementsLycee
        lycee:
            targetEntity: Lycee
            inversedBy: changementsCordee
    lifecycleCallbacks: {  }
