CEC\TutoratBundle\Entity\ContactLyceeReference:
  type: entity
  table: null
  repositoryClass: CEC\TutoratBundle\Entity\ContactLyceeReferenceRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    annee:
      type: integer
    role:
      type: string
      length: 255
  lifecycleCallbacks: {  }
