CEC\TutoratBundle\Entity\Enseignant:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        prenom:
            type: string
            length: 255
            nullable: true
        nom:
            type: string
            length: 255
        role:
            type: string
            length: 255
        email:
            type: string
            length: 255
            nullable: true
        telephoneFixe:
            type: string
            length: 255
            nullable: true
        telephonePortable:
            type: string
            length: 255
            nullable: true
        commentaires:
            type: text
            nullable: true
        dateCreation:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        dateModification:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        lycee:
            targetEntity: Lycee
            inversedBy: enseignants
    lifecycleCallbacks: {  }
