CEC\TutoratBundle\Entity\Groupe:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        niveau:
            type: string
            length: 255
        typeDeTutorat:
            type: string
            length: 255
        lieu:
            type: string
            length: 255
        debut:
            type: datetime
        fin:
            type: time
        rendezVous:
            type: string
            length: 255
        dateCreation:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        dateModification:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToMany:
        lycees:
            targetEntity: Lycee
            inversedBy: groupes
    oneToMany:
        lyceensParAnnee:
            targetEntity: CEC\TutoratBundle\Entity\GroupeEleves
            mappedBy: groupe
            cascade: ["persist", "remove"]
            orphanRemoval: true
        tuteursParAnnee:
            targetEntity: CEC\TutoratBundle\Entity\GroupeTuteurs
            mappedBy: groupe
            cascade: ["persist", "remove"]
            orphanRemoval: true
        seances:
            targetEntity: Seance
            mappedBy: groupe
            cascade: ["remove"]
    lifecycleCallbacks: {  }
