CEC\TutoratBundle\Entity\Groupe:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        niveau:
            type: string
            length: 255
        typeDeTutorat:
            type: string
            length: 255
        lieu:
            type: string
            length: 255
        debut:
            type: datetime
        fin:
            type: time
        anneeScolaire:
            type: anneescolaire
        rendezVous:
            type: string
            length: 255
        dateCreation:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        dateModification:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToMany:
        lycees:
            targetEntity: Lycee
            inversedBy: groupes
    oneToMany:
        lyceens:
            targetEntity: \CEC\MembreBundle\Entity\Eleve
            mappedBy: groupe
        tuteurs:
            targetEntity: CEC\MembreBundle\Entity\Membre
            mappedBy: groupe
        seances:
            targetEntity: Seance
            mappedBy: groupe
            cascade: ["remove"]
    lifecycleCallbacks: {  }
