CEC\TutoratBundle\Entity\GroupeEleves:
    type: entity
    table: null
    repositoryClass: CEC\TutoratBundle\Entity\GroupeElevesRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        anneeScolaire:
            type: anneescolaire
    manyToOne:
        groupe:
            targetEntity: \CEC\TutoratBundle\Entity\Groupe
            inversedBy: lyceensParAnnee
        lyceen:
            targetEntity: \CEC\MembreBundle\Entity\Eleve
            inversedBy: groupeParAnnee
    lifecycleCallbacks: {  }
