CEC\TutoratBundle\Entity\Groupe:
    type: entity
    table: null
    repositoryClass: CEC\TutoratBundle\Entity\GroupeRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        niveau:
            type: string
            length: 255
        typeDeTutorat:
            type: string
            length: 255
        lieu:
            type: string
            length: 255
        debut:
            type: datetime
        fin:
            type: datetime
        rendezVous:
            type: string
            length: 255
        annee:
            type: integer
        dateCreation:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        dateModification:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToMany:
        lycees:
            targetEntity: Lycee
            inversedBy: groupes
    oneToMany:
        lyceens:
            targetEntity: ChangementGroupeLyceen
            mappedBy: groupe
        tuteurs:
            targetEntity: ChangementGroupeTuteur
            mappedBy: groupe
        seances:
            targetEntity: Seance
            mappedBy: groupe
    lifecycleCallbacks: {  }
