CEC\TutoratBundle\Entity\Lycee:
    type: entity
    table: null
    repositoryClass: CEC\TutoratBundle\Entity\LyceeRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nom:
            type: string
            length: 255
        adresse:
            type: string
            length: 255
        codePostal:
            type: integer
        ville:
            type: string
            length: 255
        statut:
            type: string
            length: 255
        telephone:
            type: string
            length: 255
        ZEP:
            type: boolean
        pivot:
            type: boolean
        dateCreation:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        dateModification:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        changementsCordee:
            targetEntity: ChangementCordeeLycee
            mappedBy: lycee
        enseignants:
            targetEntity: ChangementEnseignantLycee
            mappedBy: lycee
    manyToMany:
        groupes:
            targetEntity: Groupe
            mappedBy: lycee
    lifecycleCallbacks: {  }
