CEC\TutoratBundle\Entity\LyceenGroupeReference:
  type: entity
  table: null
  repositoryClass: CEC\TutoratBundle\Entity\LyceenGroupeReferenceRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    classe:
      type: string
      length: 255
  lifecycleCallbacks: {  }
