CEC\TutoratBundle\Entity\Seance:
    type: entity
    table: null
    repositoryClass: CEC\TutoratBundle\Entity\SeanceRepository
    fields:
        id:
            type: integer
            id: true
            generator:
            strategy: AUTO
        lieu:
            type: string
            length: 255
        debut:
            type: datetime
        fin:
            type: datetime
        dateCreation:
            type: datetime
        dateModification:
            type: datetime
    manyToOne:
        groupe:
            targetEntity: Groupe
            inversedBy: seances
    manyToMany:
        tuteurs:
            targetEntity: CEC\MembreBundle\Entity\Membre
            inversedBy: seances
    lifecycleCallbacks: {  }
