<?php

namespace CEC\TutoratBundle\Entity;

use Doctrine\ORM\EntityRepository;
use CEC\TutoratBundle\Entity\Cordee;
use CEC\TutoratBundle\Entity\Lycee;
use CEC\MainBundle\Classes\AnneeScolaire;

/**
 * ChangementCordeeLyceeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangementCordeeLyceeRepository extends EntityRepository
{
    /**
     * Retourne tous les changements de partenariat pour une cordée et antérieurs à une année scolaire.
     *
     * @param CEC\TutoratBundle\Entity\Cordee $cordee: la cordee
     * @param CEC\MainBundle\Class\AnneeScolaire $anneeScolaire: l'année scolaire
     */
    public function findByCordeeBeforeAnneeScolaire(Cordee $cordee, AnneeScolaire $anneeScolaire = null)
    {
        if (!$anneeScolaire) $anneeScolaire = new AnneeScolaire();
        
         return $this->createQueryBuilder('r')
             ->where('r.annee = :annee')
             ->setParameter('annee', $anneeScolaire->getAnneeScolaire())
             ->innerJoin('r.cordee', 'c', 'WITH', 'c.id = :cordee_id')
             ->setParameter('cordee_id', $cordee->getId())
             ->getQuery()
             ->getResult();
    }
    
    /**
     * Retourne tous les changements de partenariat pour un lycée et antérieurs à une année scolaire.
     *
     * @param CEC\TutoratBundle\Entity\Lycee $lycee: le lycée
     * @param CEC\MainBundle\Class\AnneeScolaire $anneeScolaire: l'année scolaire
     */
    public function findByLyceeBeforeAnneeScolaire(Lycee $lycee, AnneeScolaire $anneeScolaire = null)
    {
        if (!$anneeScolaire) $anneeScolaire = new AnneeScolaire();
        
         return $this->createQueryBuilder('r')
             ->where('r.annee = :annee')
             ->setParameter('annee', $anneeScolaire->getAnneeScolaire())
             ->innerJoin('r.lycee', 'l', 'WITH', 'l.id = :lycee_id')
             ->setParameter('lycee_id', $lycee->getId())
             ->getQuery()
             ->getResult();
    }
}
