<?php

namespace CEC\TutoratBundle\Entity;

use Doctrine\ORM\EntityRepository;
use CEC\MainBundle\Utility\AnneeScolaire;

/**
 * CordeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CordeeRepository extends EntityRepository
{
    /**
     * Retourne le compte des cordées actives pour l'année scolaire indiquée.
     * On retourne le nombre de cordées actives, c'est-à-dire les cordées contenant des lycées
     * dont un groupe appartient à l'année scolaire indiquée en argument.
     *
     * @param AnneeScolaire $anneeScolaire Année scolaire
     * @return integer Compte des cordées actives.
     */
    public function comptePourAnneeScolaire(AnneeScolaire $anneeScolaire)
    {
        $query = $this->createQueryBuilder('c')
            ->select('COUNT(DISTINCT c)')
            ->join('c.lycees', 'l')
            ->join('l.groupes', 'g')
            ->where('g.anneeScolaire = :annee_scolaire')
            ->setParameter('annee_scolaire', $anneeScolaire->getAnneeInferieure())
            ->getQuery();
        return $query->getSingleScalarResult();
    }
}
