<?php

namespace CEC\TutoratBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnseignantLyceeReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignantLyceeReferenceRepository extends EntityRepository
{
}
