<?php

namespace CEC\TutoratBundle\Entity;

use Doctrine\ORM\EntityRepository;

use CEC\MainBundle\AnneeScolaire\AnneeScolaire;

/**
 * GroupeTuteursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeTuteursRepository extends EntityRepository
{

}
