<?php

namespace CEC\TutoratBundle\Entity;

use Doctrine\ORM\EntityRepository;
use CEC\MainBundle\Classes\AnneeScolaire;
use CEC\TutoratBundle\Entity\Lycee;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends EntityRepository
{
    /**
     * Récupère les groupes pour un lycée spécifique, et l'année actuelle
     *
     * @param CEC\TutoratBundle\Entity\Lycee $lycee
     */
    public function findByLyceeForCurrentYear(Lycee $lycee)
    {
        $anneeScolaire = new AnneeScolaire();
        return $this->findByAnnee($anneeScolaire->getAnneeScolaire());
    }
}
