<?php

namespace CEC\TutoratBundle\Entity;

use Doctrine\ORM\EntityRepository;

use CEC\MainBundle\AnneeScolaire\AnneeScolaire;

/**
 * GroupeElevesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeElevesRepository extends EntityRepository
{
	/**
	* Fonction renvoyant le nombre de tutorés actifs en tutorat pour une année scolaire donnée
	*
	*/
	public function comptePourAnneeScolaire(\CEC\MainBundle\AnneeScolaire\AnneeScolaire $anneeScolaire)
	{
		$query = $this->createQueryBuilder('ge')
            ->select('COUNT(DISTINCT ge)')
            ->where('ge.anneeScolaire = :annee_scolaire')
            ->setParameter('annee_scolaire', $anneeScolaire->getAnneeInferieure())
            ->getQuery();
        return $query->getSingleScalarResult();
	}
}
