<?php

namespace CEC\TutoratBundle\Entity;

use Doctrine\ORM\EntityRepository;

use CEC\MainBundle\AnneeScolaire\AnneeScolaire;

/**
 * GroupeTuteursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeTuteursRepository extends EntityRepository
{

	/**
	* Fonction renvoyant le nombre de tuteurs actifs en tutorat pour une année scolaire donnée
	*
	*/
	public function comptePourAnneeScolaire(\CEC\MainBundle\AnneeScolaire\AnneeScolaire $anneeScolaire)
	{
		$query = $this->createQueryBuilder('gt')
            ->select('COUNT(DISTINCT gt)')
            ->where('gt.anneeScolaire = :annee_scolaire')
            ->setParameter('annee_scolaire', $anneeScolaire->getAnneeInferieure())
            ->getQuery();
        return $query->getSingleScalarResult();
	}
}
