<?php

namespace CEC\TutoratBundle\Entity;

use Doctrine\ORM\EntityRepository;
use CEC\MainBundle\Utility\AnneeScolaire;

/**
 * LyceenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LyceenRepository extends EntityRepository
{
    /**
     * Retourne le compte des lycéens suivis pour l'année scolaire indiqué.
     * On retourne le nombre lycéens qui sont dans un groupe dont l'année scolaire
     * correspond à celle passée en argument.
     *
     * @param AnneeScolaire $anneeScolaire Année scolaire
     * @return integer Compte des lycéens suivis.
     */
    public function comptePourAnneeScolaire(AnneeScolaire $anneeScolaire)
    {
        $query = $this->createQueryBuilder('l')
            ->select('COUNT(DISTINCT l)')
            ->join('l.groupe', 'g')
            ->where('g.anneeScolaire = :annee_scolaire')
            ->setParameter('annee_scolaire', $anneeScolaire->getAnneeInferieure())
            ->getQuery();
        return $query->getSingleScalarResult();
    }
}
