<?php

namespace CEC\TutoratBundle\Entity;

use Doctrine\ORM\EntityRepository;
use CEC\TutoratBundle\Entity\Groupe;

/**
 * SeanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeanceRepository extends EntityRepository
{
    /**
     * Find seances for a groupe and still to come
     *
     * @param Groupe $groupe: the groupe
     * @return ArrayCollection
     */
    public function findComingByGroupe(Groupe $groupe)
    {
        $query = $this->createQueryBuilder('s')
            ->where('s.groupe = :groupe_id')
            ->setParameter('groupe_id', $groupe->getId())
            ->andWhere('s.fin > :maintenant')
            ->setParameter('maintenant', new \DateTime())
            ->getQuery();
        return $query->getResult();
    }
}
