parameters:
#    cec_activite.example.class: CEC\ActiviteBundle\Example

services:
#    cec_activite.example:
#        class: %cec_activite.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
