cec_secteur_fundraising:
    resource: "@CECSecteurFundraisingBundle/Controller/"
    type:     annotation
    prefix:   /internal

cec_activite:
    resource: "@CECActiviteBundle/Controller/"
    type:     annotation
    prefix:   /internal

cec_tutorat:
    resource: "@CECTutoratBundle/Resources/config/routing.yml"
    prefix:   /internal

cec_membre:
    resource: "@CECMembreBundle/Controller/"
    type:     annotation
    prefix:   /internal

cec_extern_site:
    resource: "@CECExternSiteBundle/Controller/"
    type:     annotation
    prefix:   /
    

# Security routes
connexion_verifications:
    pattern: /internal/connexion/verifications
connexion:
    pattern: /internal/connexion
    defaults: { _controller: CECMembreBundle:Securite:connexion }
deconnexion:
    pattern: /internal/deconnexion    

# FOSJsRoutingBundle (needed for adesigns/calendar-bundle)
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# adesigns/calendar-bundle
adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"
    
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
