jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        CEC\MembreBundle\Entity\Membre: sha512

    providers:
        membres:
            entity: { class: CECMembreBundle:Membre }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        intern:
            pattern:    ^/
            form_login:
                check_path: /connexion/verifications
                login_path: /connexion
            logout:
                path:   /deconnexion
                target: /
            anonymous: ~

    access_control:
        - { path: ^/connexion$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connexion/oubli$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
