jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        CEC\MembreBundle\Entity\Membre:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    providers:
        membres:
            entity: { class: CECMembreBundle:Membre, property: prenom }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        intern:
            pattern:    ^/internal
            form_login:
                check_path: /internal/connexion/verifications
                login_path: /internal/connexion
            logout:
                path:   /internal/deconnexion
                target: /internal
            anonymous: ~

    access_control:
        - { path: ^/internal/connexion$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/internal, roles: ROLE_USER }
