toutes_cordees:
    pattern: /cordees
    defaults: { _controller: CECTutoratBundle:Cordees:toutes }
anciennes_cordees:
    pattern: /cordees/anciennes
    defaults: { _controller: CECTutoratBundle:Cordees:anciennes }
cordee:
    pattern:  /cordees/{cordee}
    defaults: { _controller: CECTutoratBundle:Cordees:voir }
    requirements:
        cordee: \d+
editer_cordee:
    pattern: /cordees/{cordee}/edition
    defaults: { _controller: CECTutoratBundle:Cordees:editer }
    requirements:
        cordee: \d+
basculer_lycee:
    pattern: /cordees/{cordee}/basculer_lycee/{lycee}
    defaults: { _controller: CECTutoratBundle:Cordees:basculerLycee }
    requirements:
        cordee:    \d+
        lycee: \d+
desactiver_cordee:
    pattern: /cordees/{cordee}/desactivation
    defaults: { _controller: CECTutoratBundle:Cordees:desactiver }
    requirements:
        cordee: \d+

tous_lycees:
    pattern: /lycees
    defaults: { _controller: CECTutoratBundle:Cordees:toutes }
lycee:
    pattern: /lycees/{lycee}
    defaults: { _controller: CECTutoratBundle:Lycees:voir }
    requirements:
        lycee: \d+
        
tous_enseignants:
    pattern: /enseignants
    defaults: { _controller: CECTutoratBundle:Enseignants:tous }
creer_enseignant:
    pattern: /enseignants/creation
    defaults: { _controller: CECTutoratBundle:Enseignants:creer }
enseignant:
    pattern: /enseignants/{enseignant}
    defaults: { _controller: CECTutoratBundle:Enseignants:voir }
    requirements:
        cordee: \d+
editer_enseignant:
    pattern: /enseignants/{enseignant}/edition
    defaults: { _controller: CECTutoratBundle:Enseignants:editer }
    requirements:
        cordee: \d+
        
tous_lyceens:
    pattern: /lyceens
    defaults: { _controller: CECTutoratBundle:Lyceens:tous }
creer_lyceen:
    pattern: /lyceens/creation
    defaults: { _controller: CECTutoratBundle:Lyceens:creer }
lyceen:
    pattern: /lyceens/{lyceen}
    defaults: { _controller: CECTutoratBundle:Lyceens:voir }
    requirements:
        lyceen: \d+
editer_lyceen:
    pattern: /lyceens/{lyceen}/edition
    defaults: { _controller: CECTutoratBundle:Lyceens:editer }
    requirements:
        lyceen: \d+
        
groupe:
    pattern: /groupes/{groupe}
    defaults: { _controller: CECTutoratBundle:Groupes:voir }
    requirements:
        groupe: \d+
editer_groupe:
    pattern: /groupes/{groupe}/edition
    defaults: { _controller: CECTutoratBundle:Groupes:editer }
    requirements:
        groupe: \d+
