toutes_cordees:
    pattern: /cordees
    defaults: { _controller: CECTutoratBundle:Cordees:toutes }
cordee:
    pattern:  /cordees/{id}
    defaults: { _controller: CECTutoratBundle:Cordees:voir }
    requirements:
        id: \d
