toutes_cordees:
    pattern: /cordees
    defaults: { _controller: CECTutoratBundle:Cordees:toutes }
cordee:
    pattern:  /cordees/{id}
    defaults: { _controller: CECTutoratBundle:Cordees:voir }
    requirements:
        id: \d+
editer_cordee:
    pattern: /cordees/{id}/edition
    defaults: { _controller: CECTutoratBundle:Cordees:editer }
    requirements:
        id: \d+
anciennes_cordees:
    pattern: /cordees/anciennes
    defaults: { _controller: CECTutoratBundle:Cordees:anciennes }
