parameters:
#    cec_tutorat.example.class: CEC\TutoratBundle\Example

services:
#    cec_tutorat.example:
#        class: %cec_tutorat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
