CEC\MembreBundle\Entity\Membre:
    type: entity
    table: null
    repositoryClass: CEC\MembreBundle\Entity\MembreRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ prenom, nom ]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        prenom:
            type: string
            length: 255
        nom:
            type: string
            length: 255
        email:
            type: string
            length: 255
        telephone:
            type: string
            length: 255
            nullable: true
        motDePasse:
            type: string
            length: 255
        promotion:
            type: integer
        actif:
            type: boolean
        dateCreation:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        dateModification:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        documents:
            targetEntity: CEC\ActiviteBundle\Entity\Document
            mappedBy: auteur
        compteRendus:
            targetEntity: CEC\ActiviteBundle\Entity\CompteRendu
            mappedBy: auteur
    manyToMany:
        secteurs:
            targetEntity: Secteur
            inversedBy: membres
        seances:
            targetEntity: CEC\TutoratBundle\Entity\Seance
            mappedBy: tuteurs
    manyToOne:
        vpLycee:
            targetEntity: CEC\TutoratBundle\Entity\Lycee
            inversedBy: vpLycees
        groupe:
            targetEntity: CEC\TutoratBundle\Entity\Groupe
            inversedBy: tuteurs
    lifecycleCallbacks:
        prePersist: [ setDefaultValues ]
