toutes_cordees:
    path: /
    defaults: { _controller: CECTutoratBundle:Cordees:toutes }

anciennes_cordees:
    path: /anciennes
    defaults: { _controller: CECTutoratBundle:Cordees:anciennes }

cordee:
    path:  /{cordee}
    defaults: { _controller: CECTutoratBundle:Cordees:voir }
    requirements:
        cordee: \d+

editer_cordee:
    path: /{cordee}/edition
    defaults: { _controller: CECTutoratBundle:Cordees:editer }
    requirements:
        cordee: \d+

basculer_lycee:
    path: /{cordee}/basculer_lycee/{lycee}
    defaults: { _controller: CECTutoratBundle:Cordees:basculerLycee }
    requirements:
        cordee:    \d+
        lycee: \d+

desactiver_cordee:
    path: /{cordee}/desactivation
    defaults: { _controller: CECTutoratBundle:Cordees:desactiver }
    requirements:
        cordee: \d+
