tous_lycees:
    path: /
    defaults: { _controller: CECTutoratBundle:Cordees:toutes }

creer_lycee:
    path: /creation/{cordee}
    defaults: { _controller: CECTutoratBundle:Lycees:creer, cordee: null }
    requirements:
        cordee: \d+

lycee:
    path: /{lycee}
    defaults: { _controller: CECTutoratBundle:Lycees:voir }
    requirements:
        lycee: \d+

editer_lycee:
    path: /{lycee}/edition
    defaults: { _controller: CECTutoratBundle:Lycees:editer }
    requirements:
        lycee: \d+

lycee_supprimer_groupe:
    path: /{lycee}/supprimer_groupe/{groupe}
    defaults: { _controller: CECTutoratBundle:Lycees:supprimerGroupe }
    requirements:
        lycee: \d+
        groupe: \d+

lycee_supprimer_enseignant:
    path: /{lycee}/supprimer_enseignant/{enseignant}
    defaults: { _controller: CECTutoratBundle:Lycees:supprimerEnseignant }
    requirements:
        lycee: \d+
        enseignant: \d+

lycee_ajouter_enseignant:
    path: /{lycee}/ajouter_enseignant
    defaults: { _controller: CECTutoratBundle:Lycees:ajouterEnseignant }
    requirements:
        lycee: \d+

lycee_supprimer_delegue:
    path: /{lycee}/supprimer_delegue/{delegue}
    defaults: { _controller: CECTutoratBundle:Lycees:supprimerDelegue }
    requirements:
        lycee: \d+
        delegue: \d+

lycee_ajouter_delegue:
    path: /{lycee}/ajouter_delegue
    defaults: { _controller: CECTutoratBundle:Lycees:ajouterDelegue }
    requirements:
        lycee: \d+

absences_lycee:
    path: /releve-presences/{lycee}
    defaults: {_controller: CECTutoratBundle:Seances:absencesLycee}
    requirements:
        lycee: \d+

participation_sorties_lycee:
    path: /participation-sorties-lycee/{lycee}
    defaults: {_controller: CECSecteurSortiesBundle:SortiesProfesseur:participationSortiesLycee}

participation_projets_lycee:
    path: /participation-projets-lycee/{lycee}
    defaults: {_controller: CECSecteurProjetsBundle:Projets:participationProjetsLycee}
