tous_lyceens:
    pattern: /
    defaults: { _controller: CECTutoratBundle:Lyceens:tous }

creer_lyceen:
    pattern: /creation
    defaults: { _controller: CECTutoratBundle:Lyceens:creer }

lyceen:
    pattern: /{lyceen}
    defaults: { _controller: CECTutoratBundle:Lyceens:voir }
    requirements:
        lyceen: \d+

editer_lyceen:
    pattern: /{lyceen}/edition
    defaults: { _controller: CECTutoratBundle:Lyceens:editer }
    requirements:
        lyceen: \d+
