supprimer_seance:
    path: /{seance}/suppression
    defaults: { _controller: CECTutoratBundle:Seances:supprimer }
    requirements:
        seance: \d+

seance:
    path: /{seance}
    defaults: { _controller: CECTutoratBundle:Seances:voir }
    requirements:
        seance: \d+


seance_basculer_tuteur:
    path: /{seance}/basculer_tuteur/{tuteur}
    defaults: { _controller: CECTutoratBundle:Seances:basculerTuteur }
    requirements:
        seance: \d+
        tuteur: \d+

seance_basculer_lyceen:
    path: /{seance}/basculer_lyceen/{lyceen}
    defaults: { _controller: CECTutoratBundle:Seances:basculerEleve }
    requirements:
        seance: \d+
        lyceen: \d+

seance_creer_acti:
    path: /{seance}/ajout_activite/{activite}
    defaults: { _controller: CECActiviteBundle:CompteRendus:creer }
    requirements:
        seance: \d+
        activite: \d+

seance_supprimer_compterendu:
    path: /{seance}/retrait_activite/{activite}
    defaults: { _controller: CECActiviteBundle:CompteRendus:supprimer }
    requirements:
        seance: \d+
        activite: \d+

absences:
    path: /releve-presences/{lyceen}
    defaults: {_controller: CECTutoratBundle:Seances:absences}
    requirements:
        lyceen: \d+
