parameters:
#    cec_main.example.class: CEC\MainBundle\Example

services:
#    cec_main.example:
#        class: %cec_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
