services:
    cec_secteur_sorties.sorties_planning_event_listener:
        class: CEC\SecteurSortiesBundle\EventListener\SortiesPlanningEventListener
        arguments: [@doctrine.orm.entity_manager, @router]
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents, priority: -1 }
