
# Routes d'édition des projets
editer_projet:
    path: /editer-projet/{slug}
    defaults: { _controller: CECSecteurProjetsBundle:Projets:editer}
    requirements:
        slug: focus-europe|good-morning-london|centrale-prepa|stage-theatre|artcessible

creer_projet:
    path: /creer-projet
    defaults: {_controller: CECSecteurProjetsBundle:Projets:creer}


#Routes d'édition des réunions d'information
creer_reunion:
    path: /creer-reunion
    defaults: { _controller: CECSecteurProjetsBundle:Reunions:creerReunion}

modifier_reunion:
    path: /editer-reunion/{id}
    defaults: {_controller: CECSecteurProjetsBundle:Reunions:modifierReunion}
    requirements:
        id: \d+

supprimer_reunion:
    path: /supprimer-reunion/{id}
    defaults: {_controller:CECSecteurProjetsBundle:Reunions:supprimerReunion}
    requirements:
        id: \d+

inscription_reunion:
    path: /inscription-reunion/{id}
    defaults: {_controller: CECSecteurProjetsBundle:Reunions:inscriptionReunion}
    requirements:
        id: \d+

desinscription_reunion:
    path: /desinscription-reunion/{id}
    defaults: {_controller: CECSecteurProjetsBundle:Reunions:desinscriptionReunion}
    requirements:
        id: \d+

# Routes de gestion des inscriptions
dossier_inscription:
    path: /dossier-inscription
    defaults: {_controller: CECSecteurProjetsBundle:Projets:uploadDossier}

ouverture_inscription:
    path: /ouverture-inscriptions
    defaults: {_controller: CECSecteurProjetsBundle:Projets:inscriptions}

projet_ajouter_lyceen:
    path: /{slug}/ajouter
    defaults: {_controller: CECSecteurProjetsBundle:Projets:ajouterLyceen}
    requirements:
        slug: focus-europe|good-morning-london|centrale-prepa|stage-theatre|artcessible

projet_supprimer_lyceen:
    path: /{slug}/supprimer/{lyceen}
    defaults: {_controller: CECSecteurProjetsBundle:Projets:supprimerLyceen}
    requirements:
        slug: focus-europe|good-morning-london|centrale-prepa|stage-theatre|artcessible
        id: \d+


# Routes d'édition des albums photos
ajouter_photos:
    path: /ajouter-photos/{id}
    defaults: {_controller: CECSecteurProjetsBundle:Albums:ajouterPhotos, id: 0}

gerer_albums:
    path: /editer-albums
    defaults: {_controller: CECSecteurProjetsBundle:Albums:gererAlbums}

gerer_album:
    path: /editer-albums/{id}
    defaults: {_controller: CECSecteurProjetsBundle:Albums:gererAlbum, image_id: 0}
    requirements:
        id: \d+
        image_id: \d+