activites_rechercher:
    path: /
    defaults: { _controller: CECActiviteBundle:Activites:rechercher }

activites_voir:
    path: /{activite}
    defaults: { _controller: CECActiviteBundle:Activites:voir }
    requirements:
        activite: \d+

activites_editer:
    path: /{activite}/edition
    defaults: { _controller: CECActiviteBundle:Activites:editer }
    requirements:
        activite: \d+

activites_creer:
    path: /creation
    defaults: { _controller: CECActiviteBundle:Activites:creer }

activites_supprimer:
    path: /{activite}/suppression
    defaults: { _controller: CECActiviteBundle:Activites:supprimer }
    requirements:
        activite: \d+

documents_supprimer:
    path: /{activite}/documents/{document}/suppression
    defaults: { _controller: CECActiviteBundle:Documents:supprimer }
    requirements:
        activite: \d+
        document: \d+

documents_creer:
    path: /{activite}/documents/creation
    defaults: { _controller: CECActiviteBundle:Documents:creer }
    requirements:
        activite: \d+