quizzActu:
    path: /{id}
    defaults: { _controller: CECActiviteBundle:QuizzActu:voir, id: 0 }
    requirements:
        id: \d+

quizzActu_editer:
    path: /editer/{id}
    defaults: { _controller: CECActiviteBundle:QuizzActu:editer }
    requirements:
        id: \d+

quizzActu_creer:
    path: /creer
    defaults: { _controller: CECActiviteBundle:QuizzActu:creer }

quizzActu_supprimer:
    path: /supprimer/{id}
    defaults: { _controller: CECActiviteBundle:QuizzActu:supprimer }
    requirements:
        id: \d+

