cec_externe_activites:
    path: /activites
    defaults: {_controller: CECExternSiteBundle:ExternSite:activites}

cec_externe_actualites:
    path: /actualites
    defaults: {_controller: CECExternSiteBundle:ExternSite:actualites}

cec_externe_cecetvous:
    path: /cecetvous
    defaults: {_controller: CECExternSiteBundle:ExternSite:cecetvous}

cec_externe_devenir_partenaire:
    path: /devenir-partenaire
    defaults: {_controller: CECExternSiteBundle:ExternSite:devenirpartenaire}

cec_externe_histoire:
    path: /histoire
    defaults: {_controller: CECExternSiteBundle:ExternSite:histoire}

cec_externe_partenaires:
    path: /partenaires
    defaults: {_controller: CECExternSiteBundle:ExternSite:partenaires}

cec_externe_structure:
    path: /structure
    defaults: {_controller: CECExternSiteBundle:ExternSite:structure}

cec_externe_accueil:
    path: /
    defaults: {_controller: CECExternSiteBundle:ExternSite:index}