cec_externe_activites:
    pattern: /activites
    defaults: {_controller: CECExternSiteBundle:ExternSite:activites}

cec_externe_actualites:
    pattern: /actualites
    defaults: {_controller: CECExternSiteBundle:ExternSite:actualites}
    
cec_externe_cecetvous:
    pattern: /cecetvous
    defaults: {_controller: CECExternSiteBundle:ExternSite:cecetvous}
    
cec_externe_devenir_partenaire:
    pattern: /devenir-partenaire
    defaults: {_controller: CECExternSiteBundle:ExternSite:devenirpartenaire}
    
cec_externe_histoire:
    pattern: /histoire
    defaults: {_controller: CECExternSiteBundle:ExternSite:histoire}
    
cec_externe_partenaires:
    pattern: /partenaires
    defaults: {_controller: CECExternSiteBundle:ExternSite:partenaires}
    
cec_externe_structure:
    pattern: /structure
    defaults: {_controller: CECExternSiteBundle:ExternSite:structure}
    
cec_externe_accueil:
    pattern: /
    defaults: {_controller: CECExternSiteBundle:ExternSite:index}