<?php

namespace CEC\SecteurProjetsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjetEleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetEleveRepository extends EntityRepository
{
}
