<?php

namespace CEC\SecteurProjetsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends EntityRepository
{

    public function loadProjet($slug)
    {
        $query = $this->createQueryBuilder('projet')
            ->where('projet.slug = :projet')
            ->setParameter('projet', $slug)
            ->getQuery();
        
        try {
            // The Query::getSingleResult() method throws an exception
            // if there is no unique record matching the criteria
            $projet = $query->getSingleResult();
        } catch (NoResultException $e) {
            throw new UsernameNotFoundException(sprintf('Impossible de trouver un projet à partir du nom "%s".', $slug), null, 0, $e);
        }

        return $projet;
    }
}
