<?php

namespace CEC\SecteurProjetsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReunionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReunionRepository extends EntityRepository
{
	/**
     * Récupère les réunions se déroulant entre deux dates spécifiques.
     *
     * @param \DateTime $dateDebut : date de début
     * @param \DateTime $dateFin   : date de fin
     * @return ArrayCollection
     */
    public function findAllBetweenDates(\DateTime $dateDebut, \DateTime $dateFin)
    {
        $query = $this->createQueryBuilder('s')
                      ->where('s.date BETWEEN :date_debut and :date_fin')
                      ->setParameter('date_debut', $dateDebut->format('Y-m-d H:i:s'))
                      ->setParameter('date_fin', $dateFin->format('Y-m-d H:i:s'))
                      ->getQuery();
        return $query->getResult();
    }
	
	public function findAllByDate()
	{
		$query = $this->createQueryBuilder('s')
                      ->where('s.date > :date')
					  ->setParameter('date', date("Y-m-d H:i:s"))
                      ->getQuery();
        return $query->getResult();
	}
}
