sorties_eleve:
    path: /sorties
    defaults: { _controller: CECSecteurSortiesBundle:SortiesEleve:voir }

anciennes_sorties_eleve:
    path: /sortiesPassees
    defaults: { _controller: CECSecteurSortiesBundle:SortiesEleve:voirAnciennes }
