sorties_professeur:
    path: /sorties
    defaults: { _controller: CECSecteurSortiesBundle:SortiesProfesseur:voir }

anciennes_sorties_professeur:
    path: /sortiesPassees
    defaults: { _controller: CECSecteurSortiesBundle:SortiesProfesseur:voirAnciennes }