sorties:
    path: /sorties
    defaults: { _controller: CECSecteurSortiesBundle:Sorties:voir }

anciennes_sorties:
    path: /sortiesPassees
    defaults: { _controller: CECSecteurSortiesBundle:Sorties:voirAnciennes }
    
editer_sortie:
    path: /sorties/{action}/{id}
    defaults: { _controller: CECSecteurSortiesBundle:Sorties:editer }
    requirements: 
        action: editer|cr|editeraveccr
        id: \d+

creer_sortie:
    path: /sorties/creer
    defaults: { _controller: CECSecteurSortiesBundle:Sorties:creer }

supprimer_sortie:
    path: /sorties/supprimer/{id}
    defaults: { _controller: CECSecteurSortiesBundle:Sorties:supprimerSortie }
    requirements: 
        id: \d+
excel_inscrits:
    path: /excel-inscrits-sortie/{id}
    defaults: {_controller: CECSecteurSortiesBundle:Sorties:excel}
    requirements:
        id: \d+

sortie_supprimer_lyceen:
    path: /sorties/{sortie}/supprimer/{lyceen}
    defaults: {_controller: CECSecteurSortiesBundle:Sorties:desinscrire}
    requirements:
        sortie: \d+
        lyceen: \d+

sortie_ajouter_lyceen:
    path: /sorties/{sortie}/ajouter
    defaults: {_controller: CECSecteurSortiesBundle:Sorties:ajouterLyceen}
    requirements:
        sortie: \d+

sortie_basculer_lyceen:
    path: /sorties/{sortie}/basculer/{lyceen}
    defaults: {_controller: CECSecteurSortiesBundle:Sorties:basculerLyceen}
    requirements:
        sortie: \d+
        lyceen: \d+