voir_eleve:
    path: /eleve/{id}
    defaults: {_controller: CECMembreBundle:Membres:voirEleve}
    requirements:
        id: \d+

tous_eleves:
    path: /eleves
    defaults: {_controller: CECMembreBundle:Membres:tousEleve}

participation_sorties:
    path: /sortiesRealisees/{lyceen}
    defaults: {_controller: CECSecteurSortiesBundle:SortiesEleve:participationSorties}

voir_professeur:
    path: /professeur/{id}
    defaults: {_controller: CECMembreBundle:Membres:voirProfesseur}
    requirements:
        id: \d+

voir_lycee:
    path: /{categorie}/lycee/{lycee}
    defaults: {_controller: CECMembreBundle:Membres:tousLycee}
    requirements:
        id: \d+
        categorie: eleves|tuteurs|professeurs

tous_professeurs:
    path: /professeurs
    defaults: {_controller: CECMembreBundle:Membres:tousProfesseur}

voir_tous_membres:
    path: /tuteurs
    defaults: {_controller: CECMembreBundle:Membres:tous}

voir_membre:
    path: /tuteur/{membre}
    defaults: {_controller: CECMembreBundle:Membres:voir}
    requirements:
        membre: \d+

creer_membre:
    path: /creation
    defaults: {_controller: CECMembreBundle:Membres:creer}

supprimer_membre:
    path: /suppression/{membre}
    defaults: {_controller: CECMembreBundle:Membres:supprimer}
    requirements:
        membre: \d+

passations:
    path: /passations
    defaults: {_controller: CECMembreBundle:Membres:passations}

retirer_buro:
    path: /passations/retirer_membre/{membre}
    defaults: {_controller: CECMembreBundle:Membres:supprimerMembreBuro}
    requirements:
        membre: \d+

gestion_eleves:
    path: /gestionEleves
    defaults: {_controller: CECMembreBundle:Membres:gestionEleves}

gestion_eleve:
    path: /gestionEleves/{eleveid}
    defaults: {_controller: CECMembreBundle:Membres:gestionEleve}
    requirements:
        membre: \d+

gestion_eleves_test:
    path: /gestionElevesTest
    defaults: {_controller: CECMembreBundle:Membres:gestionElevesTest}