voir_eleve:
    path: /eleve/{id}
    defaults: {_controller: CECMembreBundle:Membres:voirEleve}
    requirements:
        id: \d+

tous_eleves:
    path: /eleves
    defaults: {_controller: CECMembreBundle:Membres:tousEleve}

voir_parent:
    path: /parent/{id}
    defaults: {_controller: CECMembreBundle:Membres:voirParent}
    requirements:
        id: \d+

tous_parents:
    path: /parents
    defaults: {_controller: CECMembreBundle:Membres:tousParent}


participation_sorties:
    path: /sortiesRealisees/{lyceen}
    defaults: {_controller: CECSecteurSortiesBundle:SortiesEleve:participationSorties}

voir_professeur:
    path: /professeur/{id}
    defaults: {_controller: CECMembreBundle:Membres:voirProfesseur}
    requirements:
        id: \d+

voir_lycee:
    path: /{categorie}/lycee/{lycee}
    defaults: {_controller: CECMembreBundle:Membres:tousLycee}
    requirements:
        id: \d+
        categorie: eleves|tuteurs|professeurs

tous_professeurs:
    path: /professeurs
    defaults: {_controller: CECMembreBundle:Membres:tousProfesseur}

voir_tous_membres:
    path: /tuteurs
    defaults: {_controller: CECMembreBundle:Membres:tous}

voir_membre:
    path: /tuteur/{membre}
    defaults: {_controller: CECMembreBundle:Membres:voir}
    requirements:
        membre: \d+

