reglages_accueil:
    path: /
    defaults: {_controller: CECMembreBundle:Reglages:infos}

reglages_infos:
    path: /infos
    defaults: {_controller: CECMembreBundle:Reglages:infos}

reglages_groupe:
    path: /groupe
    defaults: {_controller: CECMembreBundle:Reglages:groupe}

reglages_secteurs:
    path: /secteurs
    defaults: {_controller: CECMembreBundle:Reglages:secteurs}

reglages_infos_eleve:
    path: /infos-eleve
    defaults: {_controller: CECMembreBundle:ReglagesEleve:infos}
    requirements:
        lyceen: \d+

reglages_groupe_eleve:
    path: /groupe-eleve
    defaults: {_controller: CECMembreBundle:ReglagesEleve:groupe}
    requirements:
        lyceen: \d+

reglages_dossier_inscription_eleve:
    path: /dossier-inscription-eleve
    defaults: {_controller: CECMembreBundle:ReglagesEleve:dossierInscription}
    requirements:
        lyceen: \d+

reglages_infos_professeur:
    path: /infos-professeur
    defaults: {_controller: CECMembreBundle:ReglagesProfesseur:infos}
    requirements:
        professeur: \d+

creer_secteur:
    path: /creer-secteur
    defaults: {_controller: CECMembreBundle:Reglages:creerSecteur}

supprimer_secteur:
    path: /supprimer_secteur
    defaults: {_controller: CECMembreBundle:Reglages:supprimerSecteur}
