securite_oubli:
    pattern: /connexion/oubli
    defaults: {_controller: CECMembreBundle:Securite:oubli}
inscriptionProfesseur:
    pattern: /inscription/professeur
    defaults: {_controller: CECMembreBundle:Securite:inscriptionProfesseur}
inscriptionEleve:
    pattern: /inscription/lyceen
    defaults: {_controller: CECMembreBundle:Securite:inscriptionEleve}
