securite_oubli:
    path: /connexion/oubli
    defaults: {_controller: CECMembreBundle:Securite:oubli}
inscriptionProfesseur:
    path: /inscription/professeur
    defaults: {_controller: CECMembreBundle:Securite:inscriptionProfesseur}
inscriptionEleve:
    path: /inscription/lyceen
    defaults: {_controller: CECMembreBundle:Securite:inscriptionEleve}

inscriptionParent:
    path: /inscription/parent
    defaults: {_controller: CECMembreBundle:Securite:inscriptionParent}
