tableau_de_bord_tuteur:
    path: /tuteur/
    defaults: {_controller: CECMembreBundle:TableauDeBord:voir}
tableau_de_bord_professeur:
    path: /professeur/
    defaults: {_controller: CECMembreBundle:TableauDeBord:voirProf}
tableau_de_bord_eleve:
    path: /eleve/
    defaults: {_controller: CECMembreBundle:TableauDeBord:voirEleve}

tableau_de_bord_parent:
    path: /parent/
    defaults: {_controller: CECMembreBundle:TableauDeBord:voirParent}