connexion_verifications:
    pattern: /connexion/verifications
connexion:
    pattern: /connexion
    defaults: { _controller: CECMembreBundle:Securite:connexion }
deconnexion:
    pattern: /deconnexion
    
membre_afficher_profil:
    pattern: /membres/{id}
    defaults: { _controller: CECMembreBundle:Profil:afficher, id: null }
    requirements:
        id: \d+
    
page_accueil:
    pattern: /
    defaults: { _controller: CECMembreBundle:Profil:afficher }
