actions_membres:
    resource: "@CECMembreBundle/Resources/config/routing/membres.yml"
    prefix:   /membres

actions_reglages:
    resource: "@CECMembreBundle/Resources/config/routing/reglages.yml"
    prefix: /reglages

actions_securite:
    resource: "@CECMembreBundle/Resources/config/routing/securite.yml"

actions_tableaudebord:
    resource: "@CECMembreBundle/Resources/config/routing/tableaudebord.yml"

actions_admin:
    resource: "@CECMembreBundle/Resources/config/routing/administration.yml"
    prefix: /buro