connexion_verifications:
    pattern: /connexion/verifications
connexion:
    pattern: /connexion
    defaults: { _controller: CECMembreBundle:Securite:connexion }
deconnexion:
    pattern: /deconnexion
    
membre:
    pattern: /membres/{membre}
    defaults: { _controller: CECMembreBundle:Profil:voir, membre: null }
    requirements:
        membre: \d+

reglages:
    pattern: /reglages
    defaults: { _controller: CECMembreBundle:Reglages:index }      
reglages_profil:
    pattern: /reglages/profil
    defaults: { _controller: CECMembreBundle:Reglages:profil }
reglages_notifications:
    pattern: /reglages/notifications
    defaults: { _controller: CECMembreBundle:Reglages:notifications }
reglages_groupes_de_tutorat:
    pattern: /reglages/tutorat
    defaults: { _controller: CECMembreBundle:Reglages:groupesDeTutorat }
reglages_secteurs:
    pattern: /reglages/secteurs
    defaults: { _controller: CECMembreBundle:Reglages:secteurs }
    
page_accueil:
    pattern: /
    defaults: { _controller: CECMembreBundle:Profil:voir, membre:null }
