connexion_verifications:
    pattern: /connexion/verifications
connexion:
    pattern: /connexion
    defaults: { _controller: CECMembreBundle:Securite:connexion }
deconnexion:
    pattern: /deconnexion
    
membre_afficher_profil:
    pattern: /membres/{id}
    defaults: { _controller: CECMembreBundle:Profil:afficher, id: null }
    requirements:
        id: \d+

reglages:
    pattern: /reglages
    defaults: { _controller: CECMembreBundle:Reglages:index }      
reglages_profil:
    pattern: /reglages/profil
    defaults: { _controller: CECMembreBundle:Reglages:profil }
reglages_notifications:    
    pattern: /reglages/notifications
    defaults: { _controller: CECMembreBundle:Reglages:notifications }
reglages_groupes_de_tutorat:
    pattern: /reglages/tutorat
    defaults: { _controller: CECMembreBundle:Reglages:groupesDeTutorat }
reglages_mes_secteurs:
    pattern: /reglages/secteurs
    defaults: { _controller: CECMembreBundle:Reglages:mesSecteurs }
    
page_accueil:
    pattern: /
    defaults: { _controller: CECMembreBundle:Profil:afficher }
