connexion_verifications:
    pattern: /connexion/verifications
connexion:
    pattern: /connexion
    defaults: { _controller: CECMembreBundle:Securite:connexion }
deconnexion:
    pattern: /deconnexion
    
membre_afficher_profil:
    pattern: /membres/{id}
    defaults: { _controller: CECMembreBundle:Profil:afficher, id: null }
    requirements:
        id: \d+

reglages:
    pattern: /reglages/
    defaults: { _controller: CECMembreBundle:Reglages:index }      
reglages_profil:
    pattern: /reglages/profile
    defaults: { _controller: CECMembreBundle:Reglages:profil }
reglages_groupes_de_tutorat:
    pattern: /reglages/groupes_de_tutorat
    defaults: { _controller: CECMembreBundle:Reglages:groupesDeTutorat }
reglages_mes_secteurs:
    pattern: /reglages/mes_secteurs
    defaults: { _controller: CECMembreBundle:Reglages:mesSecteurs }
    
page_accueil:
    pattern: /
    defaults: { _controller: CECMembreBundle:Profil:afficher }
