parameters:
    cec_membre.component.authentication.handler.login_success_handler.class: CEC\MembreBundle\Component\Authentication\Handler\LoginSuccessHandler

services:
    cec_membre.component.authentication.handler.login_success_handler:
        class:  %cec_membre.component.authentication.handler.login_success_handler.class%
        arguments:  [@service_container, @router, @security.context]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
