CEC\MembreBundle\Entity\Membre:
    properties:
        prenom:
            - NotBlank: ~
        nom:
            - NotBlank: ~
        motDePasse:
            - NotBlank: ~
            - MinLength: 5
        email:
            - NotBlank: ~
            - Email: ~
        telephone:
            - Regex: "/^((0[67] ?)|\+33 ?[67] ?)([0-9]{2} ?){4}$/"
        promotion:
            - NotBlank: ~
            - Min: 1900
            - Max: 9999
        dateCreation:
            - NotBlank: ~
            - DateTime: ~
        dateModification:
            - NotBlank: ~
            - DateTime: ~

CEC\MembreBundle\Entity\Secteur:
    properties:
        nom:
            - NotBlank: ~
        dateCreation:
            - NotBlank: ~
            - DateTime: ~
        dateModification:
            - NotBlank: ~
            - DateTime: ~
            