services:
    cec_tutorat.seances_planning_event_listener:
        class: CEC\CalendrierBundle\EventListener\SeancesPlanningEventListener
        arguments: [@doctrine.orm.entity_manager, @router]
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }
