<?php

namespace CEC\ActiviteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompteRenduRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteRenduRepository extends EntityRepository
{
}
