<?php

namespace CEC\ActiviteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizzActuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizzActuRepository extends EntityRepository
{
}
