<?php

namespace CEC\ActiviteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizzActuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizzActuRepository extends EntityRepository
{
    /**
     * Reécriture de findAll() pour avoir le résultat classé par ordre de semaine
     *
     * @return array Résultats de la recherche.
     */
    public function findAll()
    {
        return $this->findBy(array(), array('semaine' => 'DESC'));
    }

    /**
     * Retourne le quizz actu de la semaine en cours (unique), null s'il n'y en a pas.
     *
     * @return QuizzActu
     */
    public function findCurrent()
    {
        $now = new \DateTime("now");
        $query = $this->createQueryBuilder('q')
                      ->where('q.semaine BETWEEN :date_debut and :date_fin')
                      ->setParameter('date_fin', $now->format('Y-m-d H:i:s'))
                      ->setParameter('date_debut', $now->modify('-6 days')->format('Y-m-d H:i:s'))
                      ->getQuery();
        return $query->getOneOrNullResult();
    }
}
