parameters:
#    cec_secteur_projets.example.class: CEC\SecteurProjetsBundle\Example

services:
#    cec_secteur_projets.example:
#        class: %cec_secteur_projets.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
