<?php

namespace CEC\MembreBundle\Entity;

use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * EleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveRepository extends EntityRepository implements UserProviderInterface
{
    /**
     * @inheritDoc
     */
    public function loadUserByUsername($username)
    {
        $query = $this->createQueryBuilder('eleve')
            ->where('CONCAT(CONCAT(eleve.prenom, \' \'), eleve.nom) = :username')
            ->setParameter('username', $username)
            ->getQuery();
        
        try {
            // The Query::getSingleResult() method throws an exception
            // if there is no unique record matching the criteria
            $user = $query->getSingleResult();
        } catch (NoResultException $e) {
            throw new UsernameNotFoundException(sprintf('Impossible de trouver un lycéen à partir du surnom "%s".', $username), 0, $e);
        }

        return $user;
    }

    /**
     * @inheritDoc
     */
    public function refreshUser(UserInterface $user)
    {
        $class = get_class($user);
        if (!$this->supportsClass($class)) {
            throw new UnsupportedUserException(sprintf('Les instances de la classe "%s" ne sont pas supportées.', $class));
        }

        return $this->find($user->getId());
    }

    /**
     * @inheritDoc
     */
    public function supportsClass($class)
    {
        return $this->getEntityName() === $class || is_subclass_of($class, $this->getEntityName());
    }

    
    /**
     * Retourne le compte des lycéens suivis pour l'année scolaire indiqué.
     * On retourne le nombre lycéens qui sont dans un groupe dont l'année scolaire
     * correspond à celle passée en argument.
     *
     * @param AnneeScolaire $anneeScolaire Année scolaire
     * @return integer Compte des lycéens suivis.
     */
    public function comptePourAnneeScolaire(AnneeScolaire $anneeScolaire)
    {
        $query = $this->createQueryBuilder('l')
            ->select('COUNT(DISTINCT l)')
            ->join('l.groupe', 'g')
            ->where('g.anneeScolaire = :annee_scolaire')
            ->setParameter('annee_scolaire', $anneeScolaire->getAnneeInferieure())
            ->getQuery();
        return $query->getSingleScalarResult();
    }

}
