<?php

namespace CEC\MembreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParentEleveRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ParentEleveRepository extends EntityRepository
{
}
